### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by lorddoig** [ogeidix/yard-rails-plugin#4]
I was getting lots of issues using Ruby 2.0.0, Yard 0.8 and Rails 3.2.14 - duplicated parameters and routes, a few crashes, there was a regex bug too.  I hacked on it pretty hard and got it all working plus some changes for my tastes.

Do you want me to pull request this stuff?  Haven't tested with Ruby < 2.0.0.

Also if you're not developing this anymore, do you have any problem if I push my fork up to rubygems once I've got it working with 1.9?

**Comment by ogeidix** [comment]
I am happy somebody took charge of this gem.
I didn't actively develop in ruby in the last year so I wasn't maintaining it anymore.

Feel free to declare your repo as the "official" one and to publish the gem.
I hope to come back to ruby soon, if that is the case I will use your gem and contribute to your fork!
